site_name: Trace Documentation
repo_url: https://github.com/shibaji7/trace
theme: 
  name: "material"
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.path

plugins:
    - search
    - glightbox
    - awesome-pages
    - mkdocstrings:
        enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
        default_handler: python
        handlers:
          python:
            paths: [".."]  
            options:
              show_root_heading: true
              show_source: true
              members_order: source
     
markdown_extensions:
    - extra
    - admonition
    - toc
    - tables
    - attr_list
    - toc:
        permalink: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - attr_list
    - md_in_html
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets:
        check_paths: true
        base_path:
          - .
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.details
    - footnotes
        
extra_javascript:
    - javascripts/mathjax.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - css/pynasonde.css

nav:
    - Home: index.md
    - Installation: user/install.md  
    - Examples:
        - Overview: examples/index.md
        - PHaRLAP + IRI 2D Ray Trace: examples/pharlap_iri.md
    - API:
        - Overview: dev/index.md
        - trace package:
            - __init__.py: dev/trace/__init__.md
            - collision.py: dev/trace/collision.md
            - dispersion.py: dev/trace/dispersion.md
            - homing.py: dev/trace/homing.md
            - pharlap.py: dev/trace/pharlap.md
            - plottrace.py: dev/trace/plottrace.md
            - rt2d.py: dev/trace/rt2d.md
            - utils.py: dev/trace/utils.md
            - density subpackage:
                - __init__.py: dev/trace/density/__init__.md
                - gemini.py: dev/trace/density/gemini.md
                - gitm.py: dev/trace/density/gitm.md
                - iri.py: dev/trace/density/iri.md
                - sami.py: dev/trace/density/sami.md
                - waccm.py: dev/trace/density/waccm.md
                - wamipe.py: dev/trace/density/wamipe.md
    - Citing: user/citing.md
    - Authors: user/authors.md
